version: 1
patchUpdated:
  generators:
  - command: . /shared/keyvault-creds.sh && for i in **/*.enc.yaml; do echo '---'; sops -d $i; done;
  - command: kustomize build .
  patchFile: flux-patch.yaml
