apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: bitshift-gitops-k8s
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: AzureCluster
    name: bitshift-gitops-k8s
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: AzureCluster
metadata:
  name: bitshift-gitops-k8s
  namespace: default
spec:
  location: westeurope
  networkSpec:
    vnet:
      name: bitshift-gitops-vnet
  resourceGroup: bitshift-gitops
