apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: linkerd
spec:
  values:
    global:
      identityTrustAnchorsPEM: |
        -----BEGIN CERTIFICATE-----
        MIIBwDCCAWagAwIBAgIQAWF/jGHmDyxNJkE2lCc9BDAKBggqhkjOPQQDAjApMScw
        JQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjAwMjEx
        MjE1OTQ5WhcNMzAwMjA4MjE1OTQ5WjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5r
        ZXJkLmNsdXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQkND2b
        bMfmNXeXKZ3HvHJnmz/VE285xAH956ocWUJ2Z8xj1hsyoqT+3DQEsdQRzMTic47B
        +4KfwdLQwaUMdnU4o3AwbjAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB
        /wIBATAdBgNVHQ4EFgQUxp9CTMUxUDT3gNVJ8E3AlwbXuIgwKQYDVR0RBCIwIIIe
        aWRlbnRpdHkubGlua2VyZC5jbHVzdGVyLmxvY2FsMAoGCCqGSM49BAMCA0gAMEUC
        IQDxxyfnYfrJtVTIJnWRXpgIvvndUb43nzKHpzeZIYcX+AIgIecixVfWpgPiEp9U
        9kaHfTbWAb6jmgs38FoY1YJ6dDk=
        -----END CERTIFICATE-----
    identity:
      issuer:
        tls:
          crtPEM: |
            -----BEGIN CERTIFICATE-----
            MIIBwTCCAWegAwIBAgIRANNcaORYPRrzQ0bsiTj++jgwCgYIKoZIzj0EAwIwKTEn
            MCUGA1UEAxMeaWRlbnRpdHkubGlua2VyZC5jbHVzdGVyLmxvY2FsMB4XDTIwMDIx
            MTIxNTk1NFoXDTIxMDIxMDIxNTk1NFowKTEnMCUGA1UEAxMeaWRlbnRpdHkubGlu
            a2VyZC5jbHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEPKKu
            ikCJfbjorxyuEZQ+6F10TM76Fsq1mOZrhlWUl4XOMdSnfoAvw+j/WbVqOP21nq0K
            iC9JeQ7o1P7RY0kNDqNwMG4wDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYB
            Af8CAQAwHQYDVR0OBBYEFOK1LhzdyT2usLXPn1+vvvtoMDuQMCkGA1UdEQQiMCCC
            HmlkZW50aXR5LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAKBggqhkjOPQQDAgNIADBF
            AiAoklEnPXI8EBNqR4IpyX3jPuRCFkItQXx02XabVYup+QIhAI5GmlyqjlJ7aWoS
            u7k+eD2GZduSjSSTPabFKBD1MCLl
            -----END CERTIFICATE-----
          keyPEM: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEINp2/wxlCO2kRJ8hn0kRMpho6SrZwdHhbD7rriw510BaoAoGCCqGSM49
            AwEHoUQDQgAEPKKuikCJfbjorxyuEZQ+6F10TM76Fsq1mOZrhlWUl4XOMdSnfoAv
            w+j/WbVqOP21nq0KiC9JeQ7o1P7RY0kNDg==
            -----END EC PRIVATE KEY-----
        crtExpiry: "2021-02-10T23:01:16Z"
