image:
  repository: docker.io/fluxcd/flux
  tag: 1.18.0
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 64Mi

helmOperator:
  create: false

git:
  url: git@github.com:181192/bitshift-gitops.git
  branch: master
  path: manifests-common,bitshift-gitops-k8s/plattform,bitshift-gitops-k8s/applications
  readonly: false
  user: bitshift-gitops-k8s
  label: bitshift-gitops-k8s-sync
  ciSkip: true
registry:
  excludeImage: aksrepos.azurecr.io/*,mcr.microsoft.com/*,index.docker.io/grafana/loki
  acr:
    enabled: true

memcached:
  resources:
    limits:
      cpu: 100m
      memory: 628Mi
    requests:
      cpu: 50m
      memory: 512Mi

prometheus:
  enabled: true

manifestGeneration: true

syncGarbageCollection:
  enabled: true

clusterRole:
  create: true

sops:
  enabled: true

initContainers:
  flux-init-keyvault:
    image: sondregj/flux-init-keyvault:1.0.0
    imagePullPolicy: Always
    args:
      - /etc/kubernetes/azure.json
      - /shared/keyvault-creds.sh
    volumeMounts:
      - mountPath: /etc/kubernetes/azure.json
        name: acr-credentials
      - mountPath: /shared
        name: shared-volume

extraVolumes:
  - name: shared-volume
    emptyDir:
      medium: Memory

extraVolumeMounts:
  - mountPath: /shared
    name: shared-volume
