apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: linkerd-system
spec:
  releaseName: linkerd
  chart:
    repository: https://helm.linkerd.io/stable
    name: linkerd2
    version: "2.7.0"
  values:
    installNamespace: false
    global:
      namespace: linkerd-system
