resources:
  - ../../manifests/nginx-ingress/overlays/linkerd
  - ../../manifests/cert-manager/overlays/linkerd
  - ../../manifests/sealed-secrets/base
  - monitoring-namespace.yaml

transformers:
  - common-annotations.yaml
  - flux-annotations.yaml
